#!/usr/bin/env python3
from pathlib import Path
import runpy

base = Path(__file__).with_name('publish_recipe_20260825_1000.py')
src = base.read_text(encoding='utf-8')
repls = {
"Purê de Abóbora com Carne para Bebê: Receita Cremosa e Fácil":"Bolinho de Batata-Doce e Frango Assado para Bebê: Receita Macia",
"pure-abobora-carne-bebe":"bolinho-batata-doce-frango-assado-bebe",
"Cluster 1 — Papinhas, purês, sopas e cremes":"Cluster 2 — BLW e alimentos para pegar com as mãos",
"Purê de Abóbora com Carne para Bebê":"Bolinho de Batata-Doce e Frango Assado para Bebê",
"purê de abóbora com carne para bebê":"bolinho de batata-doce e frango assado para bebê",
"papinha de abóbora com carne":"bolinho de batata-doce e frango assado",
"Purê espesso de abóbora com carne moída bem cozida, com textura ajustável para a alimentação complementar.":"Bolinho assado e macio de batata-doce com frango bem desfiado, com formato adaptável às habilidades da criança.",
"'recipeCategory': 'Almoço e jantar'":"'recipeCategory': 'Almoço, jantar e lanche'",
"'keywords': 'purê de abóbora com carne para bebê, alimentação complementar, papinha de abóbora com carne'":"'keywords': 'bolinho de batata-doce e frango assado para bebê, BLW, alimentação complementar, bolinho macio para bebê'",
"'recipeYield': '2 porções pequenas'":"'recipeYield': '8 bolinhos pequenos'",
"200 g de abóbora cabotiá ou moranga, descascada e cortada em cubos":"200 g de batata-doce cozida e amassada",
"100 g de carne bovina moída":"100 g de frango cozido e bem desfiado",
"2 colheres (sopa) de cebola bem picada":"2 colheres (sopa) de farinha de aveia",
"Água suficiente para o cozimento":"1 colher (sopa) de cebola bem picada",
"Cozinhe a abóbora em pouca água até ficar muito macia.":"Cozinhe a batata-doce até ficar muito macia e amasse com um garfo.",
"Em outra panela, cozinhe a carne moída com a cebola, mexendo e desfazendo os grumos, até ficar completamente cozida.":"Cozinhe completamente o frango e desfie muito bem, deixando fios curtos e macios.",
"Amasse a abóbora com um garfo e ajuste a umidade com pequenas quantidades da água do cozimento.":"Misture batata-doce, frango, farinha de aveia e cebola até formar uma massa úmida que mantenha o formato.",
"Misture a carne bem desmanchada ao purê e adapte a textura às habilidades da criança.":"Modele em formatos adequados às habilidades da criança e asse até firmar por fora, mantendo o interior macio.",
"'Purê de Abóbora com Carne para Bebê'. Show a thick, spoonable pumpkin puree with finely crumbled well-cooked ground beef visibly mixed through it, warm orange pumpkin color, realistic homemade texture.":"'Bolinho de Batata-Doce e Frango Assado para Bebê'. Show several soft homemade baked sweet-potato and shredded-chicken finger-food patties, lightly golden outside, moist tender orange interior, rustic irregular handmade shapes.",
"Serve in a small shallow handmade neutral ceramic bowl on a light oak family dining table":"Arrange the baked patties on a matte neutral ceramic plate on a light oak family dining table",
"The puree must be thick rather than liquid, with fork-mashed texture and small soft beef granules.":"The patties must look soft and easy to break, not crispy, fried, dry or hard; show one gently broken open to reveal the moist sweet-potato and fine chicken texture.",
"Este purê de abóbora com carne é uma opção simples para o almoço ou jantar quando a criança já iniciou a alimentação complementar. A proposta é deixar a abóbora bem macia e a carne moída totalmente cozida e desmanchada, formando um preparo espesso que pode ser adaptado com o garfo conforme as habilidades da criança.":"Este bolinho de batata-doce e frango é uma preparação assada, macia e fácil de adaptar para crianças que já iniciaram a alimentação complementar e conseguem lidar com alimentos em pedaços. A batata-doce ajuda a unir a massa e o frango deve ficar completamente cozido e bem desfiado. O tamanho e o formato precisam acompanhar as habilidades individuais da criança.",
"<li>200 g de abóbora cabotiá ou moranga, descascada e cortada em cubos</li>\n<li>100 g de carne bovina moída</li>\n<li>2 colheres (sopa) de cebola bem picada</li>\n<li>Água suficiente para o cozimento</li>":"<li>200 g de batata-doce cozida e amassada</li>\n<li>100 g de frango cozido e bem desfiado</li>\n<li>2 colheres (sopa) de farinha de aveia</li>\n<li>1 colher (sopa) de cebola bem picada</li>",
"<li>Cozinhe a abóbora em pouca água até ficar muito macia e fácil de amassar com o garfo.</li>\n<li>Enquanto isso, coloque a carne moída e a cebola em outra panela. Cozinhe em fogo médio, mexendo e desfazendo os grumos, até que a carne esteja completamente cozida.</li>\n<li>Escorra a maior parte da água da abóbora, reservando um pouco. Amasse com o garfo até formar um purê espesso.</li>\n<li>Misture a carne bem desmanchada ao purê. Se necessário, acrescente pequenas colheradas da água do cozimento para ajustar a consistência sem deixar o prato líquido.</li>\n<li>Espere amornar e confira a textura antes de servir.</li>":"<li>Cozinhe a batata-doce até ficar muito macia. Escorra e amasse com um garfo.</li>\n<li>Cozinhe o frango completamente e desfie muito bem, deixando fios curtos e macios.</li>\n<li>Misture a batata-doce, o frango, a farinha de aveia e a cebola até obter uma massa úmida que mantenha o formato. Se estiver muito seca, corrija com uma pequena quantidade da água do cozimento da batata.</li>\n<li>Modele bolinhos achatados ou alongados, escolhendo o formato de acordo com as habilidades da criança, e coloque em assadeira forrada.</li>\n<li>Asse em forno preaquecido a 200 °C até os bolinhos firmarem e dourarem levemente por fora. O centro deve continuar macio. Espere amornar antes de servir.</li>",
"O resultado ideal é cremoso e espesso, permanecendo na colher sem escorrer como sopa. A carne deve estar em grânulos pequenos e macios, sem blocos compactos. O Ministério da Saúde orienta que, no início da alimentação complementar, os alimentos sejam oferecidos amassados e que a consistência evolua gradualmente, em vez de permanecer sempre liquidificada.":"O bolinho deve ficar firme o suficiente para ser segurado, mas macio a ponto de se desfazer com pouca pressão entre os dedos. Evite assar até criar uma crosta dura ou deixar o interior seco. O Ministério da Saúde orienta que a consistência evolua gradualmente e informa que alimentos macios em pedaços grandes podem ser oferecidos para a criança pegar com a mão, conforme suas habilidades.",
"Para uma criança no começo da alimentação complementar, amasse a abóbora com bastante cuidado e desfaça muito bem os grumos da carne. Conforme ela desenvolve habilidades para lidar com texturas mais marcadas, deixe o purê menos uniforme. Não é necessário transformar tudo em líquido: a ideia é adaptar a consistência de forma progressiva.":"O formato não deve ser definido apenas pela idade. Para quem já consegue pegar alimentos com a mão, modele de maneira que seja fácil segurar e mantenha o bolinho bem macio. Para crianças que ainda não lidam bem com pedaços, esta receita pode ser servida desmanchada e amassada com o garfo. A refeição deve acontecer com a criança sentada e sob supervisão.",
"O Ministério da Saúde informa que alimentos in natura ou minimamente processados podem ser oferecidos junto ao leite materno a partir dos 6 meses e recomenda comida amassada quando a criança começa a receber outros alimentos.":"O Ministério da Saúde informa que alimentos in natura ou minimamente processados podem ser oferecidos junto ao leite materno a partir dos 6 meses e orienta a evolução gradual da consistência, de comida amassada para pedaços macios conforme a criança desenvolve habilidades.",
"A abóbora cabotiá pode ser trocada por moranga. Para variar o preparo, outra carne bovina moída pode ser usada desde que seja completamente cozida e fique com textura macia. Alterações para crianças com alergias ou necessidades específicas devem ser discutidas com profissional habilitado.":"A batata-doce pode ser trocada por mandioquinha bem cozida e amassada. A farinha de aveia pode precisar de ajuste porque a umidade dos ingredientes varia. Alterações relacionadas a alergias ou necessidades específicas devem ser discutidas com profissional habilitado.",
"Como a receita contém carne moída, não vamos indicar um prazo único de conservação sem contexto de temperatura e manipulação. Para reduzir risco, prepare porções pequenas, mantenha higiene no preparo e siga orientações oficiais de conservação de alimentos. Não guarde para outra refeição a porção que já teve contato com a colher ou a boca da criança.":"Como a receita contém frango cozido, não vamos indicar um prazo único de conservação sem conhecer temperatura e manipulação. Prepare porções pequenas, mantenha higiene no preparo e siga orientações oficiais de conservação. Não guarde para outra refeição a porção que já teve contato com a boca da criança.",
"<h3>Precisa bater no liquidificador?</h3>\n<p>Não. Amasse a abóbora com garfo e desmanche bem a carne. Isso permite controlar melhor a espessura e evoluir a textura gradualmente.</p>\n<h3>Posso deixar a carne separada do purê?</h3>\n<p>Sim. Misturar é uma opção prática, mas os componentes também podem ser oferecidos lado a lado, desde que a textura esteja adequada às habilidades da criança.</p>\n<h3>O purê pode ficar bem ralo?</h3>\n<p>Evite acrescentar água em excesso. Um preparo espesso facilita manter a comida na colher e permite perceber melhor a textura dos alimentos.</p>":"<h3>O bolinho precisa ficar crocante?</h3>\n<p>Não. Para esta proposta, o objetivo é que ele fique apenas firme por fora e continue macio por dentro. Se estiver duro ou seco, não é a textura desejada.</p>\n<h3>Posso fazer sem farinha de aveia?</h3>\n<p>A quantidade de farinha serve para ajudar a massa a manter o formato. Dependendo da umidade da batata-doce, pode ser possível reduzir a quantidade, desde que o bolinho continue macio e não se desfaça completamente ao assar.</p>\n<h3>Precisa oferecer o bolinho inteiro?</h3>\n<p>Não. O tamanho e o formato devem ser adaptados às habilidades da criança. Ele também pode ser partido ou desmanchado com o garfo antes de servir.</p>",
"['Alimentação complementar', 'Papinhas e purês', 'Abóbora', 'Carne']":"['Alimentação complementar', 'BLW', 'Bolinho assado', 'Frango', 'Batata-doce']",
"('purê de abóbora' in title and 'carne' in title)":"('bolinho de batata-doce' in title and 'frango' in title)",
"Record duplicate prevention for morning recipe":"Record duplicate prevention for BLW pillar recipe",
"Add unique AI food photo for pumpkin beef puree":"Add unique AI food photo for sweet potato chicken patties",
"Record published pumpkin beef puree recipe":"Record published BLW sweet potato chicken recipe"
}
for a,b in repls.items():
    src = src.replace(a,b)
start = src.find("<h2>Receitas relacionadas</h2>")
end = src.find("<h2>Referências oficiais</h2>")
if start != -1 and end != -1:
    related = """<h2>Receitas relacionadas</h2>\n<ul>\n<li><a href='https://www.receitasparapequenos.site/2026/08/almondegas-de-frango-com-abobrinha-para.html'>Almôndegas de Frango com Abobrinha para Bebês</a></li>\n<li><a href='https://www.receitasparapequenos.site/2026/07/bolinho-de-arroz-e-legumes-para-bebes.html'>Bolinho de Arroz e Legumes para Bebês</a></li>\n<li><a href='https://www.receitasparapequenos.site/2026/07/panqueca-de-batata-doce-para-bebes.html'>Panqueca de Batata-Doce para Bebês</a></li>\n</ul>\n"""
    src = src[:start] + related + src[end:]
tmp = Path(__file__).with_name('_generated_20260826_1000.py')
tmp.write_text(src, encoding='utf-8')
try:
    runpy.run_path(str(tmp), run_name='__main__')
finally:
    tmp.unlink(missing_ok=True)
